# Just type 'docker-compose up' in this directory.
version: "2"
services:
  postgresql-imal:
    image: postgres:12
    container_name: postgres-vardplatspusslet
    ports:
      - 5442:5432
    volumes:
      - pg-vardplatspusslet:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vardplatspusslet
    restart: on-failure

volumes:
  pg-vardplatspusslet:
    driver: local
